version: '3.3'

volumes:
  pg_quiz_data:

services:

  db:
    image: postgres:16
    container_name: quiz_db
    env_file: .env
    volumes:
      - pg_quiz_data:/var/lib/postgresql/data
  quiz:
    build: .
    container_name: quiz_app
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:8000
    command: ["/app/docker/app.sh"]
